sudo: required
env:
  #matrix:

branches:
  only:
  - cat80x

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade docker
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull revivie/scientific-linux:latest

script:
 # Run tests in Container
 - sudo docker run --rm=true -v `pwd`:/CATTools:rw hepsw/cvmfs-cms:latest /bin/bash -c "/CATTools/setup.sh"

notifications:
  email: false
